import Image from "next/image";
import "./globals.css";
import Link from "next/link";
import { BsGithub } from "react-icons/bs";

export const metadata = {
  title: "Subbit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="flex absolute z-10">
          <Link href={"/"} id="logo" className="ml-5">
            <Image
              src={"/static/logo.png"}
              height={1000}
              width={1000}
              className="w-[5rem]"
            />
          </Link>
        </nav>
        {children}
        <footer className="w-full">
          <div className="flex p-4 px-10 justify-between bg-[#171717]">
            <div>
              <h1 className="text-sm text-gray-400">By Sahil Bhor</h1>
            </div>
            <div>
              <Link href={"https://github.com/Sahil-B07"}>
                <BsGithub className="scale-[1.5]" />
              </Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
