services:
  backend:
    image: python:3.11
    container_name: subbit_backend
    command: bash -c "pip install -r /code/requirements.txt && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
      - ./backend/media:/code/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=subbit
      - POSTGRES_USER=sahilbhor
      - POSTGRES_PASSWORD=Object@23
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    image: node:18-alpine
    container_name: subbit_frontend
    working_dir: /app
    command: /bin/sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/public/static:/app/public/static
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    container_name: subbit_db
    environment:
      POSTGRES_DB: subbit
      POSTGRES_USER: sahilbhor
      POSTGRES_PASSWORD: Object@23
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
